inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**"
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
