inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"

Documentation:
  Enabled: false

Lint/UnreachableLoop:
  Exclude:
    - "lib/google/cloud/credentials.rb"
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/config.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/credentials.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/credentials.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-core.rb"
Style/CaseEquality:
  Exclude:
    - "lib/google/cloud/config.rb"
