inherit_gem:
    google-style: google-style.yml

Lint/UselessAssignment:
    Enabled: false
Metrics/BlockLength:
    Exclude:
        - "acceptance/*.rb"
Style/IfUnlessModifier:
    Enabled: false
Style/RedundantAssignment:
    Enabled: false
Style/RedundantBegin:
    Enabled: false
